# Generated by Django 3.0.7 on 2020-06-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_collectid_str', models.CharField(max_length=32)),
                ('cl_userid_str', models.CharField(max_length=32)),
                ('cl_filmid_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_commentid_str', models.CharField(max_length=32)),
                ('c_content_str', models.CharField(max_length=32)),
                ('c_fl_id_str', models.CharField(max_length=32)),
                ('c_user_id', models.CharField(max_length=32)),
                ('c_time_str', models.CharField(max_length=32)),
                ('c_goodNum_int', models.CharField(max_length=32)),
                ('c_replyNum_int', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_filmid_str', models.CharField(max_length=32)),
                ('fl_title_str', models.CharField(max_length=32)),
                ('fl_intro_str', models.CharField(max_length=32)),
                ('fl_grade_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lb_labelid_str', models.CharField(max_length=32)),
                ('lb_name_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rl_id_str', models.CharField(max_length=32)),
                ('rl_fl_id_str', models.CharField(max_length=32)),
                ('rl_lb_id_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rp_id_str', models.CharField(max_length=32)),
                ('rp_c_id_str', models.CharField(max_length=32)),
                ('rp_content_str', models.CharField(max_length=32)),
                ('rp_user_id_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='tb_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id_str', models.CharField(max_length=32)),
                ('user_name_str', models.CharField(max_length=32)),
                ('user_headPictureUrl_str', models.CharField(max_length=32)),
                ('user_gender_str', models.CharField(max_length=32)),
                ('user_password_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
