# Generated by Django 3.0.7 on 2020-06-30 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_auto_20200629_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_title_str', models.CharField(max_length=32)),
                ('fl_type_str', models.CharField(max_length=32)),
                ('fl_grade_str', models.CharField(max_length=32)),
                ('fl_mainRole_str', models.CharField(max_length=32)),
                ('fl_anotherName_str', models.CharField(max_length=32)),
                ('fl_director_str', models.CharField(max_length=32)),
                ('fl_scenarist_str', models.CharField(max_length=32)),
                ('fl_length_str', models.CharField(max_length=32)),
                ('fl_language_str', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='tb_User',
            new_name='tbUser',
        ),
        migrations.DeleteModel(
            name='tb_Film',
        ),
    ]
