# Generated by Django 3.0.7 on 2020-06-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20200630_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_collectid_str', models.CharField(max_length=32)),
                ('cl_userid_str', models.CharField(max_length=32)),
                ('cl_filmid_str', models.CharField(max_length=32)),
            ],
        ),
    ]
