# Generated by Django 3.0.7 on 2020-06-30 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0005_auto_20200630_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fl_title_str', models.TextField()),
                ('fl_type_str', models.TextField()),
                ('fl_data_str', models.DateField()),
                ('fl_commentNum_int', models.IntegerField()),
                ('fl_replyNum_int', models.IntegerField()),
                ('fl_grade_str', models.FloatField()),
                ('fl_mainRole_str', models.TextField()),
                ('fl_anotherName_str', models.TextField()),
                ('fl_director_str', models.TextField()),
                ('fl_scenarist_str', models.TextField()),
                ('fl_length_str', models.CharField(max_length=32)),
                ('fl_language_str', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_anotherName_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_director_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_grade_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_language_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_mainRole_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_scenarist_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_title_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='tablefilm',
            name='fl_type_str',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='tablefilm',
            name='fl_length_str',
            field=models.CharField(default='', max_length=32),
        ),
    ]
