# Generated by Django 3.0.7 on 2020-06-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0006_auto_20200630_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdata',
            name='fl_anotherName_str',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_commentNum_int',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_data_str',
            field=models.DateField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_director_str',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_grade_str',
            field=models.FloatField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_language_str',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_length_str',
            field=models.CharField(max_length=32, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_mainRole_str',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_replyNum_int',
            field=models.IntegerField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_scenarist_str',
            field=models.TextField(null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_type_str',
            field=models.TextField(null=0),
        ),
    ]
