# Generated by Django 3.0.7 on 2020-06-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0007_auto_20200630_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdata',
            name='fl_data_str',
            field=models.TextField(null=0),
        ),
    ]
