# Generated by Django 3.0.7 on 2020-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0009_auto_20200630_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdata',
            name='fl_anotherName_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_commentNum_int',
            field=models.IntegerField(blank=True, default='', null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_data_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_director_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_grade_str',
            field=models.FloatField(blank=True, default='', null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_language_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_length_str',
            field=models.CharField(blank=True, max_length=32, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_mainRole_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_replyNum_int',
            field=models.IntegerField(blank=True, default='', null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_scenarist_str',
            field=models.TextField(blank=True, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_type_str',
            field=models.TextField(blank=True, null=0),
        ),
    ]
