# Generated by Django 3.0.7 on 2020-06-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0010_auto_20200630_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmdata',
            name='fl_commentNum_int',
        ),
        migrations.RemoveField(
            model_name='filmdata',
            name='fl_grade_str',
        ),
        migrations.RemoveField(
            model_name='filmdata',
            name='fl_replyNum_int',
        ),
        migrations.AddField(
            model_name='filmdata',
            name='fl_commentNum',
            field=models.CharField(blank=True, max_length=32, null=0),
        ),
        migrations.AddField(
            model_name='filmdata',
            name='fl_grade',
            field=models.CharField(blank=True, max_length=32, null=0),
        ),
        migrations.AddField(
            model_name='filmdata',
            name='fl_replyNum',
            field=models.CharField(blank=True, max_length=32, null=0),
        ),
    ]
