# Generated by Django 3.0.7 on 2020-07-01 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0011_auto_20200630_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdata',
            name='fl_commentNum',
            field=models.CharField(blank=True, max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_grade',
            field=models.CharField(blank=True, max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_length_str',
            field=models.CharField(blank=True, max_length=128, null=0),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_replyNum',
            field=models.CharField(blank=True, max_length=128, null=0),
        ),
    ]
