# Generated by Django 3.0.7 on 2020-07-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0012_auto_20200701_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ft_title', models.TextField()),
                ('ft_tag', models.CharField(blank=True, max_length=128, null=0)),
            ],
        ),
    ]
