# Generated by Django 3.0.7 on 2020-07-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0014_auto_20200701_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmtag',
            name='ft_title',
            field=models.TextField(max_length=1280, unique=True),
        ),
    ]
