# Generated by Django 3.0.7 on 2020-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0016_auto_20200701_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmtag',
            name='ft_title',
            field=models.TextField(max_length=2560),
        ),
    ]
