# Generated by Django 3.0.7 on 2020-07-02 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0017_auto_20200702_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmtag',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
