# Generated by Django 3.0.7 on 2020-07-04 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0018_auto_20200702_1428'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coll',
        ),
        migrations.DeleteModel(
            name='TableFilm',
        ),
        migrations.DeleteModel(
            name='tb_Collection',
        ),
        migrations.DeleteModel(
            name='tb_Comment',
        ),
        migrations.DeleteModel(
            name='tb_Label',
        ),
        migrations.DeleteModel(
            name='tb_Relation',
        ),
        migrations.DeleteModel(
            name='tb_Review',
        ),
        migrations.DeleteModel(
            name='tbUser',
        ),
    ]
