# Generated by Django 3.0.7 on 2020-07-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0019_auto_20200704_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content_str', models.TextField(max_length=2560)),
                ('c_user_name', models.CharField(max_length=128, unique=True)),
                ('com_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sex', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=32)),
                ('user_personal', models.CharField(default='当前显示为默认标签，您可以点击右方修改进行修改', max_length=100)),
                ('user_movie_tag', models.CharField(choices=[('terrify', '惊悚'), ('action', '动作'), ('love', '爱情'), ('adventure', '冒险'), ('western', '欧美'), ('funny', '搞笑'), ('japan_and_korea', '日韩'), ('crime', '犯罪'), ('disaster', '灾难')], default='当前为默认电影标签，您可以点击右方修改自定义标签', max_length=100)),
                ('user_pic', models.CharField(default='/static/images/userPic.jpg', max_length=100)),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('user_address', models.CharField(default='当前显示为默认地址，您可以点击右方修改进行修改', max_length=100)),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['c_time'],
            },
        ),
    ]
