# Generated by Django 3.0.7 on 2020-07-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0020_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_user_name',
            field=models.CharField(max_length=128),
        ),
    ]
