# Generated by Django 3.0.7 on 2020-07-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0021_auto_20200704_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_film_name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
