# Generated by Django 3.0.7 on 2020-07-04 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0022_comment_c_film_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='c_film_name',
            new_name='c_film_title',
        ),
    ]
