# Generated by Django 3.0.7 on 2020-07-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0024_remove_comment_c_film_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='c_film_title',
            field=models.CharField(default='坏孩子的秋天', max_length=128),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_user_name',
            field=models.CharField(default='01', max_length=128),
        ),
    ]
