# Generated by Django 3.0.7 on 2020-07-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0027_auto_20200705_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmdata',
            name='fl_commentNum',
            field=models.CharField(blank=True, default='500', max_length=128),
        ),
        migrations.AlterField(
            model_name='filmdata',
            name='fl_grade',
            field=models.CharField(blank=True, default='5.6', max_length=128),
        ),
    ]
