# Generated by Django 3.0.7 on 2020-07-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0029_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_movie_tag',
            field=models.CharField(choices=[('terrify', '惊悚'), ('action', '动作'), ('love', '爱情'), ('adventure', '冒险'), ('western', '欧美'), ('funny', '搞笑'), ('japan_and_korea', '日韩'), ('crime', '犯罪'), ('disaster', '灾难')], default=' ', max_length=100),
        ),
    ]
