# Generated by Django 3.0.7 on 2020-07-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0030_auto_20200706_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coll_user_name', models.CharField(default='01', max_length=128)),
                ('coll_film_title', models.CharField(default='坏孩子的秋天', max_length=128)),
                ('coll_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
